# Generated by Django 3.1.3 on 2020-11-21 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_remove_comment_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='article',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
