# Generated by Django 3.1.3 on 2020-11-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20201127_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(choices=[('Science', 'Science'), ('Politics', 'Politics'), ('Technics', 'Technics'), ('History', 'History'), ('Music', 'Music')], max_length=20),
        ),
    ]
