# Generated by Django 3.1.3 on 2020-11-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201121_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
