# Generated by Django 3.1.3 on 2020-11-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20201127_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(choices=[('Sc', 'Science'), ('Pl', 'Politics'), ('Th', 'Technics'), ('Hs', 'History'), ('Ms', 'Music')], max_length=20),
        ),
    ]
