# Generated by Django 3.1.3 on 2020-12-05 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20201127_1935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
