# Generated by Django 3.1.3 on 2021-01-19 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20210119_1914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
